pr: none

trigger:
- master

pool: GCP2

variables:
- group: SYSTEM_VAR_GROUP

jobs:
- job: setupEnvironment
  steps:
  - task: adopt-openjdk-installer@1
    inputs:
      majorVersion: '11'
      useLatestOption: 'latest'
      jdkArchitectureOption: 'x64'
      jvmOption: 'hotspot'
  # Setup SBT first for the master pipeline build
  - task: setup-sbt@1
    displayName: 'Setup SBT for pipeline'
    inputs:
      sbtVersion: '1.5.1'
      
- job: buildAndTestProject       
  steps:
  # Set the Sonatype credentials for SBT
  - script: |
      pwd
      cd $(System.DefaultWorkingDirectory)/.git/
      ls -la
      pwd
    displayName: 'cd into project directory'

  # Compile the project
  - script: |
      sbt compile
    displayName: 'sbt compile'

  # Run the tests
  - script: |
      sbt test
    displayName: 'sbt test'
