pr: none

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Setup SBT first for the master pipeline build
  - task: setup-sbt@1
    displayName: 'Setup SBT for pipeline'
    inputs:
      sbtVersion: '1.5.1'

  # Compile the project
  - script: |
      sbt compile
    displayName: 'sbt compile'

  # Run the tests
  - script: |
      sbt compile
    displayName: 'sbt test'
