pr: none

trigger:
- master

pool: GCP2

steps:
  # Everything needs Java to run
  - task: Bash@3
    displayName: 'Download java sdk'
    inputs:
      targetType: 'inline'
      script: 'wget https://builds.openlogic.com/downloadJDK/openlogic-openjdk/8u262-b10/openlogic-openjdk-8u262-b10-linux-x64.tar.gz -O $(Build.ArtifactStagingDirectory)/java8.tar.gz'
  - task: JavaToolInstaller@0
    displayName: 'Install java sdk'
    inputs:
      versionSpec: "8"
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: "$(Build.ArtifactStagingDirectory)/java8.tar.gz"
      jdkDestinationDirectory: ""

  # Setup SBT first for the master pipeline build
  - task: setup-sbt@1
    displayName: 'Setup SBT for pipeline'
    inputs:
      sbtVersion: '1.5.1'

  # Set the Sonatype credentials for SBT
  - script: |
      cd $(System.DefaultWorkingDirectory)
      ls -la
    displayName: 'cd into project directory'

  # Compile the project
  - script: |
      sbt compile
    displayName: 'sbt compile'

  # Run the tests
  - script: |
      sbt test
    displayName: 'sbt test'
