pr: none

trigger:
- master

pool: GCP2

variables:
- group: SYSTEM_VAR_GROUP

jobs:
- job: setupEnvironment
  steps:
  - task: Bash@3
    displayName: 'Download java sdk.'
    inputs:
      targetType: 'inline'
      script: 'wget https://builds.openlogic.com/downloadJDK/openlogic-openjdk/8u262-b10/openlogic-openjdk-8u262-b10-linux-x64.tar.gz -O $(Build.ArtifactStagingDirectory)/java8.tar.gz'
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "8"
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: "$(Build.ArtifactStagingDirectory)/java8.tar.gz"
      jdkDestinationDirectory: ""
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo JAVA_HOME set to -> $JAVA_HOME
        echo JAVA_HOME_8_X64 set to -> $JAVA_HOME_8_X64
        echo which java returns
        which java
        
- job: buildAndTestProject       
  steps:
  # Setup SBT first for the master pipeline build
  - task: setup-sbt@1
    displayName: 'Setup SBT for pipeline'
    inputs:
      sbtVersion: '1.5.1'

  # Set the Sonatype credentials for SBT
  - script: |
      pwd
      cd $(System.DefaultWorkingDirectory)/.git/
      ls -la
      pwd
    displayName: 'cd into project directory'

  # Compile the project
  - script: |
      sbt compile
    displayName: 'sbt compile'

  # Run the tests
  - script: |
      sbt test
    displayName: 'sbt test'
