addSbtPlugin("com.codecommit"    % "sbt-github-actions"  % "0.12.0")
addSbtPlugin("com.github.sbt"      % "sbt-unidoc"          % "0.5.0")
addSbtPlugin("com.geirsson"      % "sbt-ci-release"      % "1.5.7")
addSbtPlugin("org.scalameta"     % "sbt-mdoc"            % "2.2.21")
// addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.8.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"             % "1.0.1")
