addSbtPlugin("com.codecommit"    % "sbt-github-actions"  % "0.10.1")
//addSbtPlugin("com.codecommit"    % "sbt-github-packages" % "0.5.2")
addSbtPlugin("com.47deg"         % "sbt-microsites"      % "1.2.1")
addSbtPlugin("com.eed3si9n"      % "sbt-unidoc"          % "0.4.3")
// addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "0.15.0")
// addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.10.0")
// addSbtPlugin("com.typesafe.sbt"  % "sbt-twirl"           % "1.4.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-site"            % "1.4.1")
addSbtPlugin("com.typesafe.sbt"  % "sbt-ghpages"         % "0.6.3")
// addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.8.0")
// addSbtPlugin("org.foundweekends" % "sbt-bintray"         % "0.6.1")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.6.1")

addSbtPlugin("au.com.onegeek" % "sbt-dotenv" % "2.1.146")
addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.7")
