name: test oracleJDK-12 Scala-2.12.13

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up oraclejdk12
      uses: actions/setup-java@v1
      with:
        java-version: 12
        architecture: x64
    - name: Run tests
      run: sbt ++2.12.10! clean test
